-- File Name		: cropcu1_upload.sql

-- File Created for	: Upload file for cropcu1

-- Created By		: Ashok Kumar.S

-- Client		: Indus Ind Bank

-- Created On		: 01-11-2011
-------------------------------------------------------------------
truncate table CU1CROP_O_TABLE;
  
insert into CU1CROP_O_TABLE
(
select 
--   CORP_KEY             CHAR(32) NULL,
    fin_cif_id,
-- ENTITY_TYPE              CHAR(30) NULL,
    'CUSTOMER',
-- CORPORATENAME_NATIVE               CHAR(80) NULL,
    gfcun,
--   RELATIONSHIP_STARTDATE    CHAR(11) NULL,
    to_char(to_date(to_char(get_date_fm_btrv(GFCOD)),'YYYYMMDD'),'DD-MON-YYYY'),
--   STATUS             CHAR(5) NULL,
    'ACTVE',
--   LEGALENTITY_TYPE         CHAR(30) NULL,
    convert_codes('LEGALENTY',GFCTP),
--   SEGMENT              CHAR(150) NULL,
--    get_segment(gfctp,gfc4r,2),
'CORPT',
-- SUBSEGMENT              CHAR(150) NULL,
 --   get_segment(gfctp,gfc4r,3),
 'CORPT',
--   WEBSITE_ADDRESS         CHAR(100) NULL,
    '',
--   KEYCONTACT_PERSONNAME    CHAR(30) NULL,
    'MIGR',
--   PHONECITYCODE         CHAR(15) NULL,
    '123',
--   PHONELOCALCODE         CHAR(15) NULL,
    '123',
--   PHONECOUNTRYCODE         CHAR(15) NULL,
    '123',
--   NOTES             CHAR(255) NULL,
    'MIGR',
--   PRINCIPLE_PLACEOPERATION    CHAR(30) NULL,
    convert_codes('CNTRY',BGBSCI),
--   BUSINESS_GROUP         CHAR(30) NULL,
    'BG1',
-- PRIMARYRM_ID             CHAR(15) NULL,
    convert_codes('RMCODE',GFACO),
--   DATE_OF_INCORPORATION    CHAR(11) NULL,
    case when BGBFDT <> 0 and get_date_fm_btrv(BGBFDT) <> 'ERROR' then 
            to_char(to_date(to_char(get_date_fm_btrv(BGBFDT)),'YYYYMMDD'),'DD-MON-YYYY')
            else to_char(to_date(to_char(get_date_fm_btrv(GFCOD)),'YYYYMMDD'),'DD-MON-YYYY')
    end,
-- DATE_OF_COMMENCEMENT        CHAR(11) NULL,
    case when BGBFDT <> 0 and get_date_fm_btrv(BGBFDT) <> 'ERROR' then 
            to_char(to_date(to_char(get_date_fm_btrv(BGBFDT)),'YYYYMMDD'),'DD-MON-YYYY')
            else ''
    end,
--   PRIMARY_SERVICE_CENTER    CHAR(30) NULL,
    fin_sol_id,
--   RELATIONSHIP_CREATEDBY    CHAR(30) NULL,
    convert_codes('RMCODE',GFACO),
--  SECTOR_CODE             CHAR(5) NULL,
    convert_codes('SECTOR',GFCA2),
--   SUBSECTOR_CODE         CHAR(5) NULL,
    convert_codes('SUBSECTOR',GFCA2),
--   TAXID             CHAR(50) NULL,
    '',
-- ENTITYCLASS             CHAR(30) NULL,
    'GOLD',
-- AVERAGE_ANNUALINCOME        CHAR(20) NULL,
    '9999999.99',
--   SOURCE_OF_FUNDS         CHAR(50) NULL,
    case when BGCCDR is null then 'MIGRATED'
	else cast(BGCCDR as varchar2(50))
	end,
--   GROUP_ID             CHAR(50) NULL,
    '',
--   GROUP_ID_CODE         CHAR(50) NULL,
    '',
--   PARENT_CIF             CHAR(38) NULL,
    '',
-- CUSTOMER_RATING_CODE        CHAR(5) NULL,
    get_segment(gfctp,gfc4r,4),
-- HEALTH_CODE             CHAR(5) NULL,
    '777',
--   RECORD_STATUS         CHAR(150) NULL,
    '',
--   EFFECTIVE_DATE         CHAR(11) NULL,
    '',
--   LINE_OF_ACTIVITY_DESC    CHAR(50) NULL,
    convert_codes('INDUSTRYTYPE',GFCA2),
--   CUST_MGR_OPIN         CHAR(240) NULL,
    '',
--   CUST_TYPE_DESC         CHAR(50) NULL,
    'Corporate',
-- CUST_STAT_CHG_DATE         CHAR(11) NULL,
    '',
-- TDS_TBL_DESC             CHAR(50) NULL,
    '',
--   CUST_SWIFT_CODE         CHAR(12) NULL,
    '',
--   IS_SWIFT_CODE_OF_BANK    CHAR(1) NULL,
    'Y',
--   CUSTDEPOSITSINOTHERBANKS     CHAR(20) NULL,
    '',
--   TOTALFUNDBASE         CHAR(25) NULL,
    '',
--   TOTALNONFUNDBASE         CHAR(25) NULL,
    '',
--   ADVANCEASONDATE         CHAR(11) NULL,
    '',
--   CUST_CONST             CHAR(5) NULL,
    convert_codes('CONST',BGBCON),
--   DOCUMENT_RECEIVED_FLAG    CHAR(1) NULL,
    '',
-- CRNCY_CODE_CORPORATE        CHAR(5) NULL,
    'SAR',
--   TRADE_SERVICES_AVAILED    CHAR(1) NULL,
    '',
-- PRIMARYSOLID             CHAR(8) NULL,
    fin_sol_id,
--   CHRG_DR_FORACID         CHAR(16) NULL,
    '',
--   CHRG_DR_SOL_ID         CHAR(8) NULL,
    '',
--   CUST_CHRG_HISTORY_FLG    CHAR(1) NULL,
    '',
--  TOT_TOD_ALWD_TIMES         CHAR(5) NULL,
    '',
--   SMALL_STR1             CHAR(50) NULL,
    '',
--   SMALL_STR2             CHAR(50) NULL,
    '',
--   SMALL_STR3             CHAR(50) NULL,
    '',
--   SMALL_STR4             CHAR(50) NULL,
    '',
--   SMALL_STR5             CHAR(50) NULL,
    '',
--   SMALL_STR6             CHAR(50) NULL,
    '',
--   SMALL_STR7             CHAR(50) NULL,
    '',
--   SMALL_STR8             CHAR(50) NULL,
    '',
--   SMALL_STR9             CHAR(50) NULL,
    '',
-- SMALL_STR10             CHAR(50) NULL,
    '',
--   MED_STR1             CHAR(100) NULL,
    '',
--   MED_STR2             CHAR(100) NULL,
    '',
--   MED_STR3             CHAR(100) NULL,
    '',
--   MED_STR4             CHAR(100) NULL,
    '',
--   MED_STR5             CHAR(100) NULL,
    '',
--   MED_STR6             CHAR(100) NULL,
    '',
--   MED_STR7             CHAR(100) NULL,
    '',
--   MED_STR8             CHAR(100) NULL,
    '',
--   MED_STR9             CHAR(100) NULL,
    '',
--   MED_STR10             CHAR(100) NULL,
    '',
--   LARGE_STR1             CHAR(250) NULL,
    '',
--   LARGE_STR2             CHAR(250) NULL,
    '',
--   LARGE_STR3             CHAR(250) NULL,
    '',
--   LARGE_STR4             CHAR(250) NULL,
    '',
--   LARGE_STR5             CHAR(250) NULL,
    '',
--   DATE1             CHAR(8) NULL,
    '',
--   DATE2             CHAR(8) NULL,
    '',
--   DATE3             CHAR(8) NULL,
    '',
--   DATE4             CHAR(8) NULL,
    '',
--   DATE5             CHAR(8) NULL,
    '',
--   DATE6             CHAR(8) NULL,
    '',
--   DATE7             CHAR(8) NULL,
    '',
--   DATE8             CHAR(8) NULL,
    '',
--   DATE9             CHAR(8) NULL,
    '',
--   DATE10             CHAR(8) NULL,
    '',
--   NUMBER1             CHAR(38) NULL,
    '',
--   NUMBER2             CHAR(38) NULL,
    '',
--   NUMBER3             CHAR(38) NULL,
    '',
--   NUMBER4             CHAR(38) NULL,
    '',
--   NUMBER5             CHAR(38) NULL,
    '',
--   NUMBER6             CHAR(38) NULL,
    '',
--   NUMBER7             CHAR(38) NULL,
    '',
--   NUMBER8             CHAR(38) NULL,
    '',
--   NUMBER9             CHAR(38) NULL,
    '',
--   NUMBER10             CHAR(38) NULL,
    '',
--   DECIMAL1             CHAR(25) NULL,
    '',
--   DECIMAL2             CHAR(25) NULL,
    '',
--   DECIMAL3             CHAR(25) NULL,
    '',
--   DECIMAL4             CHAR(25) NULL,
    '',
--   DECIMAL5             CHAR(25) NULL,
    '',
--   DECIMAL6             CHAR(25) NULL,
    '',
--   DECIMAL7             CHAR(25) NULL,
    '',
--   DECIMAL8             CHAR(25) NULL,
    '',
--   DECIMAL9             CHAR(25) NULL,
    '',
--   DECIMAL10             CHAR(25) NULL,
    '',
-- CORE_CUST_ID             CHAR(9) NULL,
    '',
--   CIFID             CHAR(32) NULL,
    fin_cif_id,
--   CREATEDBYSYSTEMID         CHAR(50) NULL,
    '',
--   CORPORATENAME_NATIVE1    CHAR(80) NULL,
    GFCUNA,
-- SHORT_NAME_NATIVE1         CHAR(10) NULL,
    substr(GFDASA,1,9),
--   OWNERAGENT             CHAR(38) NULL,
    '',
--   PRIMARYRMLOGIN_ID         CHAR(50) NULL,
    convert_codes('RMCODE',GFACO),
--   SecondRMLogin_ID         CHAR(50) NULL,
    '',
-- TERTIARYRMLOGIN_ID         CHAR(50) NULL,
    '',
--   ACCESSOWNERGROUP         CHAR(38) NULL,
    '',
-- ACCESSOWNERSEGMENT         CHAR(50) NULL,
    '',
--   ACCESSOWNERBC         CHAR(38) NULL,
    '',
--   ACCESSOWNERAGENT         CHAR(38) NULL,
    '',
-- ACCESSASSIGNEEAGENT         CHAR(38) NULL,
    '',
-- PRIMARYPARENTCOMPANY        CHAR(80) NULL,
    '',
-- COUNTRYOFPRINCIPALOPERATION    CHAR(100) NULL,
    convert_codes('CNTRY',BGBSCI),
-- PARENTCIF_ID             CHAR(50) NULL,
    '',
--   CHARGELEVELCODE         CHAR(50) NULL,
    '',
--   COUNTRYOFORIGIN         CHAR(50) NULL,
    convert_codes('CNTRY',BGBSCI),
--   COUNTRYOFINCORPORATION    CHAR(50) NULL,
    convert_codes('CNTRY',BGBSCI),
--   INTUSERFIELD1         CHAR(38) NULL,
    '',
--   INTUSERFIELD2         CHAR(38) NULL,
    '',
--   INTUSERFIELD3         CHAR(38) NULL,
    '',
--   INTUSERFIELD4         CHAR(38) NULL,
    '',
--   INTUSERFIELD5         CHAR(38) NULL,
    '',
--   StrUserField1         CHAR(100) NULL,
    convert_codes('SALUT',BGISAL),
--   StrUserField2         CHAR(100) NULL,
    '',
--   StrUserField3         CHAR(100) NULL,
    'N',
--   StrUserField4         CHAR(100) NULL,
    '',
--   StrUserField5         CHAR(100) NULL,
    '',
--   StrUserField6         CHAR(100) NULL,
    'N',
--   StrUserField7         CHAR(100) NULL,
    '',
--   StrUserField8         CHAR(100) NULL,
    convert_codes_const('CORP_CONST_DETAILS',gfctp,
case when trim(convert_codes('CNTRY',nvl(gfcnap,gfcnal)))= 'SA' then 'SA' else 'NONSA' end),   -- DEFAULT BLANK--Changed for Mock 3,
--   StrUserField9         CHAR(100) NULL,
    '',
--   StrUserField10         CHAR(100) NULL,
    '',
--   StrUserField11         CHAR(100) NULL,
    '',
--   StrUserField12         CHAR(100) NULL,
    '',
--   StrUserField13         CHAR(100) NULL,
    '',
--   StrUserField14         CHAR(100) NULL,
    '',
--   StrUserField15         CHAR(100) NULL,
    '',
--   StrUserField16         CHAR(100) NULL,
    convert_codes('CNTRY',BGBSCI),
--   StrUserField17         CHAR(100) NULL,
    '',
--   StrUserField18         CHAR(100) NULL,
    '',
--   StrUserField19         CHAR(100) NULL,
    '',
--   StrUserField20         CHAR(100) NULL,
    get_segment(gfctp,gfc4r,1),
--   StrUserField21         CHAR(100) NULL,
    '',
--   StrUserField22         CHAR(100) NULL,
    '',
--   StrUserField23         CHAR(100) NULL,
    '',
--   StrUserField24         CHAR(100) NULL,
    '',
--   StrUserField25         CHAR(100) NULL,
    '',
--   StrUserField26         CHAR(100) NULL,
    '',
--   StrUserField27         CHAR(100) NULL,
    convert_codes('CNTRY',BGBSCI),
--   StrUserField28         CHAR(100) NULL,
    '',
--   StrUserField29         CHAR(100) NULL,
    '',
--   StrUserField30         CHAR(100) NULL,
    '',
--   DateUserField1         CHAR(8) NULL,
    '',
--   DateUserField2         CHAR(8) NULL,
    '',
--   DateUserField3         CHAR(8) NULL,
    '',
--   DateUserField4         CHAR(8) NULL,
    '',
--   DateUserField5         CHAR(8) NULL,
    '',
--   NATIVELANGCODE         CHAR(10) NULL,
     convert_codes('LANG',GFLNM),                               -- DEFAULT SET TO 'ENGLISH'
--   CUST_HLTH             CHAR(200) NULL,
    '777',
--   LASTSUBMITTEDDATE         CHAR(11) NULL,
    '',
-- RISK_PROFILE_SCORE         CHAR(38) NULL,
    '',
--   RISK_PROFILE_EXPIRY_DATE    CHAR(11) NULL,
    '',
-- OUTSTANDING_MORTAGE         CHAR(20) NULL,
    '',
--   CORPORATE_NAME         CHAR(100) NULL,
    gfcun,
--   SHORT_NAME             CHAR(10) NULL,
--    substr(gfdas,1,9),
	case when GFDAS is not null then substr(GFDAS,1,9) else '.' end,
--   SHORT_NAME_NATIVE         CHAR(10) NULL,
    substr(gfdasa,1,9),
-- REGISTRATION_NUMBER         CHAR(38) NULL,
    case when BGBTRN is not null then BGBTRN else cast('REG:1111' as nvarchar2(10))end,
--   CHANNELSACCESSED         CHAR(500) NULL,
    '',
-- ZIP                 CHAR(100) NULL,
    '',
--   BACKENDID             CHAR(50) NULL,
    '',
--   DELINQUENCYFLAG         CHAR(3) NULL,
    '',
-- SUSPEND_FLAG             CHAR(1) NULL,
    case when status = 'SUSPENDED' then 'Y'
	else '' end,
--   SUSPEND_NOTES         CHAR(2000) NULL,
    '',
--   SUSPEND_REASON         CHAR(2000) NULL,
    '',
--   BLACKLIST_FLAG         CHAR(1) NULL,
    '',
--   BLACKLIST_NOTES         CHAR(2000) NULL,
    '',
--   BLACKLIST_REASON         CHAR(2000) NULL,
    '',
--   NEGATIVE_FLAG         CHAR(1) NULL,
    '',
--   NEGATIVE_NOTES         CHAR(2000) NULL,
    '',
--   NEGATIVE_REASON         CHAR(2000) NULL,
    '',
--   DSAID             CHAR(50) NULL,
    'UBSADMIN',
--   CUSTASSET_CLASSIFICATION    CHAR(5) NULL,
    'Type1',
--   CLASSIFIED_ON         CHAR(11) NULL,
    '',
-- CUST_CREATION_MODE         CHAR(1) NULL,
    '',
--   INCREMENTALDATEUPDATE    CHAR(11) NULL,
    '',
--   LANG_CODE             CHAR(50) NULL,
    convert_codes('LANG',GFLNM),
--  TDS_CUST_ID             CHAR(9) NULL,
    '',
-- OTHERLIMITS             CHAR(20) NULL,
    '',
-- CORE_INTROD_CUST_ID         CHAR(9) NULL,
    '',
-- INTROD_NAME             CHAR(40) NULL,
    '',
--   INTROD_STAT_CODE         CHAR(5) NULL,
    '',
-- ENTITY_STAGE             CHAR(200) NULL,
    '',
-- ENTITY_STEP_STATUS         CHAR(50) NULL,
    '',
--   EMAIL2             CHAR(50) NULL,
    BGCEID,
--   CUST_GRP             CHAR(50) NULL,
    '',
--   CUST_CONST_CODE         CHAR(5) NULL,
    convert_codes('CONST',BGBCON),
--   CUSTASSET_CLSFTION_CODE    CHAR(5) NULL,
    '',
--   LEGALENTITY_TYPE_CODE    CHAR(5) NULL,
    '',
-- REGION_CODE             CHAR(5) NULL,
    '',
--   PRIORITY_CODE         CHAR(8) NULL,
    'High',
-- BUSINESS_TYPE_CODE         CHAR(5) NULL,
    '99999',
--   RELATIONSHIP_TYPE_CODE    CHAR(5) NULL,
    'New',
--   CRNCY_CODE             CHAR(5) NULL,
    'SAR',
-- STR1                 CHAR(1) NULL,
    '',
-- STR2                 CHAR(8) NULL,
    '',
-- STR3                 CHAR(1) NULL,
    '',
-- STR4                 CHAR(1) NULL,
    '',
-- STR5                 CHAR(8) NULL,
    '',
-- STR6                 CHAR(100) NULL,
    '',
-- STR7                 CHAR(100) NULL,
    '',
-- STR8                 CHAR(100) NULL,
    '',
-- STR9                 CHAR(100) NULL,
    '',
--   STR10             CHAR(100) NULL,
    '',
--   STR11             CHAR(200) NULL,
    '',
--   STR12             CHAR(200) NULL,
    '',
--   STR13             CHAR(200) NULL,
    '',
--   STR14             CHAR(200) NULL,
    '',
--   STR15             CHAR(200) NULL,
    '',
--   AMOUNT1             CHAR(20) NULL,
    '',
--   AMOUNT2             CHAR(20) NULL,
    '',
--   AMOUNT3             CHAR(20) NULL,
    '',
--   AMOUNT4             CHAR(20) NULL,
    '',
--   AMOUNT5             CHAR(20) NULL,
    '',
-- INT1                 CHAR(38) NULL,
    '',
-- INT2                 CHAR(38) NULL,
    '',
-- INT3                 CHAR(38) NULL,
    '',
-- INT4                 CHAR(38) NULL,
    '',
-- INT5                 CHAR(38) NULL,
    '',
--   Flag1             CHAR(10) NULL,
    '',
--   Flag2             CHAR(10) NULL,
    '',
--   Flag3             CHAR(10) NULL,
    '',
--   Flag4             CHAR(10) NULL,
    '',
--   Flag5             CHAR(10) NULL,
    '',
-- MLUSERFIELD1             CHAR(80) NULL,
    '',
-- MLUSERFIELD2             CHAR(80) NULL,
    '',
-- MLUSERFIELD3             CHAR(80) NULL,
    '',
-- MLUSERFIELD4             CHAR(80) NULL,
    '',
-- MLUSERFIELD5             CHAR(80) NULL,
    '',
-- MLUSERFIELD6             CHAR(80) NULL,
    '',
-- MLUSERFIELD7             CHAR(80) NULL,
    '',
--MLUSERFIELD8             CHAR(80) NULL,
    '',
-- MLUSERFIELD9             CHAR(80) NULL,
    '',
-- MLUSERFIELD10         CHAR(100) NULL,
    '',
--   UNIQUEGROUPFLAG         CHAR(1) NULL,
    '',
--   BANK_ID             CHAR(8) NULL,
    get_param('BANK_ID'),
--   ZAKAT_DEDUCTION         CHAR(1) NULL,
    '',
-- ASSET_CLASSIFICATION        CHAR(1) NULL,
    '',
--  CUSTOMER_LEVEL_PROVISIONING    CHAR(1) NULL,
    '',
--   ISLAMIC_BANKING_CUSTOMER    CHAR(1) NULL,
    '',
--   PREFERREDCALENDAR         CHAR(50) NULL,
    '',
--   IDTYPEC1             CHAR(50) NULL,
    fin_cif_id,
--   IDTYPEC2             CHAR(50) NULL,
    '',
--   IDTYPEC3             CHAR(50) NULL,
    '',
--   IDTYPEC4             CHAR(50) NULL,
    '',
--   IDTYPEC5             CHAR(50) NULL,
    '',
--   IDTYPEC6             CHAR(50) NULL,
    '',
--   IDTYPEC7             CHAR(50) NULL,
    '',
--   IDTYPEC8             CHAR(50) NULL,
    '',
--   IDTYPEC9             CHAR(50) NULL,
    '',
--   IDTYPEC10             CHAR(50) NULL,
    '',
-- CORPORATE_NAME_ALT1         CHAR(80) NULL,
    '',
--   short_Name_alt1          CHAR(99) NULL,
    '',
--   KEYCONTACT_PERSONNAME_ALT1    CHAR(30) NULL,
    '',
--   PARENT_CIF_ALT1          CHAR(38) NULL,
    '',
-- BOCREATEDDBYLOGINID         CHAR(50) NULL
     ''
      from
 map_cif
    inner join migr_customer_corp on map_cif.leg_cust_number = GFCPNC
    left join BGPF on bgcus = GFCPNC
);

      COMMIT;
   
exit;