-- File Name		: cropcu2_upload.sql

-- File Created for	: Upload file for cropcu2

-- Created By		: Ashok Kumar.S

-- Client		: Indus Ind Bank

-- Created On		: 01-11-2011
-------------------------------------------------------------------

create or replace
procedure cropcu2_upload
   as

begin

   Begin

EXECUTE IMMEDIATE 'truncate table CU2CROP_O_TABLE';
  
  end;

insert into CU2CROP_O_TABLE
(
select
--   CORP_KEY		 CHAR(50) NULL,
	map_cif.fin_cif_id,
--   CIF_ID		 CHAR(32) NULL,
	map_cif.fin_cif_id,
-- CORP_REP_KEY		 CHAR(38) NULL,
	'',
--   ADDRESSCATEGORY  	 CHAR(100) NULL,
	'P',
--   START_DATE		 CHAR(17) NULL,
	to_char(to_date(to_char(pack_mig_eq3.get_date_fm_btrv(GFPF.GFCOD)),'DD-MM-YYYY'),'DD-MON-YYYY'),
--   PhoneNo1LocalCode	 CHAR(20) NULL,
	'',
--   PhoneNo1CityCode	 CHAR(20) NULL,
	'',
-- PhoneNo1CountryCode 	 CHAR(20) NULL,
	'',
--   PhoneNo2LocalCode	 CHAR(20) NULL,
	'',
--   PhoneNo2CityCode	 CHAR(20) NULL,
	'',
--  PhoneNo2CountryCode	 CHAR(20) NULL,
	'',
--   FaxNoLocalCode	 CHAR(20) NULL,
	'',
--   FaxNoCityCode  	 CHAR(20) NULL,
	'',
--   FaxNoCountryCode	 CHAR(20) NULL,
	'',
--   Email		 CHAR(50) NULL,
	'',
--   PagerNoLocalCode  	 CHAR(20) NULL,
	'',
--   PagerNoCityCode	 CHAR(20) NULL,
	'',
--   PagerNoCountryCode	 CHAR(20) NULL,
	'',
--   TelexLocalCode	 CHAR(20) NULL,
	'',
--   TelexCityCode	 CHAR(20) NULL,
	'',
--   TelexCountryCode	 CHAR(20) NULL,
	'',
--   HOUSE_NO		 CHAR(10) NULL,
	'',
-- PREMISE_NAME		 CHAR(50) NULL,
	'',
--   BUILDING_LEVEL	 CHAR(10) NULL,
	'',
--   STREET_NO		 CHAR(50) NULL,
	'',
-- STREET_NAME		 CHAR(50) NULL,
	'',
--   SUBURB		 CHAR(50) NULL,
	'',
--   LOCALITY_NAME	 CHAR(50) NULL,
	'',
-- TOWN			 CHAR(50) NULL,
	'',
--   DOMICILE		 CHAR(50) NULL,
	'',
--   CITY_CODE		 CHAR(100) NULL,
	'DOMEN',
--   STATE_CODE		 CHAR(100) NULL,
	'USA',
--  ZIP			 CHAR(100) NULL,
	'470072',
-- COUNTRY_CODE		 CHAR(100) NULL,
	'INDIA',
--   SMALL_STR1		 CHAR(50) NULL,
	'',
--   SMALL_STR2		 CHAR(50) NULL,
	'',
--   SMALL_STR3		 CHAR(50) NULL,
	'',
--   SMALL_STR4		 CHAR(50) NULL,
	'',
--   SMALL_STR5		 CHAR(50) NULL,
	'',
--   SMALL_STR6		 CHAR(50) NULL,
	'',
--   SMALL_STR7		 CHAR(50) NULL,
	'',
--   SMALL_STR8		 CHAR(50) NULL,
	'',
--   SMALL_STR9		 CHAR(50) NULL,
	'',
--  SMALL_STR10		 CHAR(50) NULL,
	'',
--   MED_STR1		 CHAR(100) NULL,
	'',
--   MED_STR2		 CHAR(100) NULL,
	'',
--   MED_STR3		 CHAR(100) NULL,
	'',
--   MED_STR4		 CHAR(100) NULL,
	'',
--   MED_STR5		 CHAR(100) NULL,
	'',
--   MED_STR6		 CHAR(100) NULL,
	'',
--   MED_STR7		 CHAR(100) NULL,
	'',
--   MED_STR8		 CHAR(100) NULL,
	'',
--   MED_STR9		 CHAR(100) NULL,
	'',
--   MED_STR10		 CHAR(100) NULL,
	'',
--   LARGE_STR1		 CHAR(250) NULL,
	'',
--   LARGE_STR2		 CHAR(250) NULL,
	'',
--   LARGE_STR3		 CHAR(250) NULL,
	'',
--   LARGE_STR4		 CHAR(250) NULL,
	'',
--   LARGE_STR5		 CHAR(250) NULL,
	'',
--   DATE1		 CHAR(17) NULL,
	'',
--   DATE2		 CHAR(17) NULL,
	'',
--   DATE3		 CHAR(17) NULL,
	'',
--   DATE4		 CHAR(17) NULL,
	'',
--   DATE5		 CHAR(17) NULL,
	'',
--   DATE6		 CHAR(17) NULL,
	'',
--   DATE7		 CHAR(17) NULL,
	'',
--   DATE8		 CHAR(17) NULL,
	'',
--   DATE9		 CHAR(17) NULL,
	'',
--   DATE10		 CHAR(17) NULL,
	'',
--   NUMBER1		 CHAR(38) NULL,
	'',
--   NUMBER2		 CHAR(38) NULL,
	'',
--   NUMBER3		 CHAR(38) NULL,
	'',
--   NUMBER4		 CHAR(38) NULL,
	'',
--   NUMBER5		 CHAR(38) NULL,
	'',
--   NUMBER6		 CHAR(38) NULL,
	'',
--   NUMBER7		 CHAR(38) NULL,
	'',
--   NUMBER8		 CHAR(38) NULL,
	'',
--   NUMBER9		 CHAR(38) NULL,
	'',
--   NUMBER10		 CHAR(38) NULL,
	'',
--   DECIMAL1		 CHAR(25) NULL,
	'',
--   DECIMAL2		 CHAR(25) NULL,
	'',
--   DECIMAL3		 CHAR(25) NULL,
	'',
--   DECIMAL4		 CHAR(25) NULL,
	'',
--   DECIMAL5		 CHAR(25) NULL,
	'',
--   DECIMAL6		 CHAR(25) NULL,
	'',
--   DECIMAL7		 CHAR(25) NULL,
	'',
--   DECIMAL8		 CHAR(25) NULL,
	'',
--   DECIMAL9		 CHAR(25) NULL,
	'',
--   DECIMAL10		 CHAR(25) NULL,
	'',
--   preferredAddrss	 CHAR(50) NULL,
	'P',
--  HoldMailInitiatedBy	 CHAR(20) NULL,
	'',
-- HoldMailFlag		 CHAR(50) NULL,
	'',
--   BusinessCenter	 CHAR(50) NULL,
	'',
--   HoldMailReason	 CHAR(200) NULL,
	'',
--   PreferredFormat	 CHAR(50) NULL,
	'STRUCTURED_FORMAT',
--   FreeTextAddress	 CHAR(2000) NULL,
	'',
--   FreeTextLabel	 CHAR(200) NULL,
	'',
--   ADDRESS_PROOF_RCVD	 CHAR(1) NULL,
	'',
--   LASTUPDATE_DATE	 CHAR(17) NULL,
	'',
--   ADDRESS_LINE1	 CHAR(45) NULL,
	'',
--   ADDRESS_LINE2	 CHAR(45) NULL,
	'',
--   ADDRESS_LINE3	 CHAR(45) NULL,
	'',
--   BANK_ID		 CHAR(8) NULL   
   	'01'
  	from map_cif
	inner join gfpf on gfpf.gfcus = map_cif.leg_cust_number
	left join map_cif_type on leg_cust_type_code = gfpf.gfctp
	where map_cif_type.leg_cust_type ='Other than Individual'
  and map_cif.fin_sol_id='0006');

      COMMIT;
   
END;